FROM ibmcom/websphere-traditional:8.5.5.12-profile
COPY target/SafetyLite.ear /tmp/
COPY libs/jt400.jar  /opt/IBM/DB2/jt400.jar 
COPY libs/jt400.jar /QIBM/ProdData/Http/Public/jt400/lib/jt400.jar 
COPY scripts /tmp/scripts

ENV PROFILE_HOME=/opt/IBM/WebSphere/AppServer/profiles/AppSrv01
ENV WAS_HOME=/opt/IBM/WebSphere/AppServer
ENV THIN_CLIENT_HOME=/opt/IBM/WebSphere/ThinClient
ENV JYTHON_VERSION=2.7.0
ENV JYTHON_INSTALLER=jython-installer-${JYTHON_VERSION}.jar
ENV PATH="${THIN_CLIENT_HOME}/java/bin:${PATH}"

RUN mkdir -pv $THIN_CLIENT_HOME \
    && mkdir -pv $THIN_CLIENT_HOME/lib \
    && mkdir -pv $THIN_CLIENT_HOME/lib/jython \
    && mkdir -pv $THIN_CLIENT_HOME/properties \
    && mkdir -pv $THIN_CLIENT_HOME/etc \
    && mkdir -pv $THIN_CLIENT_HOME/logs \
    && mkdir -pv $THIN_CLIENT_HOME/profiles \
    && ls -ald $THIN_CLIENT_HOME $WAS_HOME/java
RUN cp -r ${WAS_HOME}/java ${THIN_CLIENT_HOME}

ADD libs/${JYTHON_INSTALLER} ${THIN_CLIENT_HOME}

RUN cd $THIN_CLIENT_HOME \
    && java -jar ${JYTHON_INSTALLER} -s -d ${THIN_CLIENT_HOME}/lib/jython \
    && rm -rf ${JYTHON_INSTALLER}

RUN ln -s $WAS_HOME/profiles/${PROFILE_NAME}/logs $HOME/logs && chown was:was $HOME/logs 

RUN cp -r ${WAS_HOME}/runtimes/com.ibm.ws.admin.client_8.5.0.jar ${THIN_CLIENT_HOME}/lib
RUN cp -r ${WAS_HOME}/plugins/com.ibm.ws.security.crypto.jar ${THIN_CLIENT_HOME}/lib
RUN cp -r ${WAS_HOME}/profiles/AppSrv01/properties/ipc.client.props ${THIN_CLIENT_HOME}/properties
RUN cp -r ${WAS_HOME}/profiles/AppSrv01/properties/soap.client.props ${THIN_CLIENT_HOME}/properties
RUN sed -i 's/soap.client.props:com.ibm.SOAP.securityEnabled=false/soap.client.props:com.ibm.SOAP.securityEnabled=true/' ${THIN_CLIENT_HOME}/properties/soap.client.props
RUN cp -r ${WAS_HOME}/profiles/AppSrv01/properties/sas.client.props ${THIN_CLIENT_HOME}/properties
RUN cp -r ${WAS_HOME}/profiles/AppSrv01/properties/ssl.client.props ${THIN_CLIENT_HOME}/properties
#Change the value of user.root to <THIN_CLIENT_HOME>.
RUN sed -i 's#user.root=/opt/IBM/WebSphere/AppServer/profiles/AppSrv01#/opt/IBM/WebSphere/ThinClient#' /opt/IBM/WebSphere/ThinClient/properties/ssl.client.props
RUN cp -r ${WAS_HOME}/profiles/AppSrv01/properties/wsjaas_client.conf ${THIN_CLIENT_HOME}/properties
COPY thinClient/wsadmin.properties ${THIN_CLIENT_HOME}/properties
COPY thinClient/thinClient.sh ${THIN_CLIENT_HOME}/

RUN wsadmin.sh -lang jython -conntype NONE -c "AdminApp.install('/tmp/SafetyLite.ear', '[ -appname SafetyLite -contextroot /SafetyLite ]')"
#RUN wsadmin.sh -lang jython -conntype NONE -f /tmp/scripts/modNameSpaceBinding.py /tmp/scripts/modNameSpaceBinding.yaml