values:
  - nodeName: ""
    serverName: ""
    templateID: ""
    jdbcProvider: ""
    implementationClass: ""
    attributes: ""
  - nodeName: ""
    serverName: ""
    templateID: ""
    jdbcProvider: ""
    implementationClass: ""
    attributes: ""
  - nodeName: ""
    serverName: ""
    templateID: ""
    jdbcProvider: ""
    implementationClass: ""
    attributes: ""
  - nodeName: ""
    serverName: ""
    templateID: ""
    jdbcProvider: ""
    implementationClass: ""
    attributes: ""
